spring.application.name=CkycApplication
server.port=8080
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/ckyc_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
ckyc.institution-code= NBFC12345
ckyc.soap-endpoint= https://cersai.gov.in/ckyc
